font_family JetBrainsMono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 9.0

include theme.conf

window_padding_width 6
single_window_margin_width 0
confirm_os_window_close 0
enable_audio_bell no
copy_on_select clipboard
strip_trailing_spaces smart

background_opacity 1.0
dynamic_background_opacity no

tab_bar_edge bottom
tab_bar_style separator
tab_separator " "
tab_title_template " {index}:{title} "
