general {
    hide_cursor = true
}

background {
    monitor =
    path = ~/.config/hypr/wallpapers/misty_peaks.jpg
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 280, 52
    position = 0, -40
    halign = center
    valign = center
    outline_thickness = 1
    outer_color = rgba(c4746eff)
    inner_color = rgba(181616dd)
    font_color = rgba(c5c9c5ff)
    placeholder_text = Password
}
