$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus --new-window
$browser = zen-browser --blank-window
$mono = qs ipc call mono

source = ~/.config/mono/hypr/monitors.conf
source = ~/.config/hypr/environment.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/keybindings.conf
