windowrule = match:class ^(org\.gnome\.Nautilus|nautilus)$, float true
windowrule = match:class ^(pavucontrol|org\.pulseaudio\.pavucontrol)$, float true
windowrule = match:class ^(pavucontrol|org\.pulseaudio\.pavucontrol)$, center true
windowrule = match:class ^(nm-connection-editor|blueman-manager)$, float true
windowrule = match:class ^(scrcpy)$, float true
windowrule = match:modal true, float true
windowrule = match:modal true, center true
